[package]
name = "rust-names"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.2"
reqwest = { version = "0.11.10", features = ["blocking"] }
random = "0.12.2"